//
// $Id: TimeBaseService.java,v 1.2 2002/05/29 18:44:36 mdb Exp $

package com.threerings.presents.client;

import com.threerings.presents.Log;
import com.threerings.presents.client.Client;
import com.threerings.presents.client.InvocationDirector;
import com.threerings.presents.data.TimeBaseCodes;

/**
 * Provides a means by which to obtain access to a time base object which
 * can be used to convert delta times into absolute times.
 */
public class TimeBaseService
    implements TimeBaseCodes
{
    /**
     * Requests the oid of the specified time base object be returned. The
     * supplied response target must provide two methods to handle the
     * responses generated by this request:
     *
     * <pre>
     *   public void handleTimeOidResponse (int invid, int timeOid);
     *   public void handleGetTimeOidFailed (int invid, String reason);
     * </pre>
     */
    public static void getTimeOid (
        Client client, String timeBase, Object rsptarget)
    {
        InvocationDirector invdir = client.getInvocationDirector();
        invdir.invoke(MODULE_NAME, GET_TIME_OID_REQUEST,
                      new Object[] { timeBase }, rsptarget);
        Log.debug("Sent getTimeOid request [timeBase=" + timeBase + "].");
    }
}
