//
// $Id: LocationCodes.java,v 1.2 2001/10/11 04:07:51 mdb Exp $

package com.threerings.crowd.client;

import com.threerings.presents.client.InvocationCodes;

/**
 * Contains codes used by the location invocation services.
 */
public interface LocationCodes extends InvocationCodes
{
    /** The module name for the location services. */
    public static final String MODULE_NAME = "location";

    /** The message identifier for a moveTo request. */
    public static final String MOVE_TO_REQUEST = "MoveTo";

    /** The response identifier for a successful moveTo request. This is
     * mapped by the invocation services to a call to {@link
     * LocationDirector#handleMoveSucceeded}. */
    public static final String MOVE_SUCCEEDED_RESPONSE = "MoveSucceeded";

    /** The response identifier for a failed moveTo request. This is
     * mapped by the invocation services to a call to {@link
     * LocationDirector#handleMoveFailed}. */
    public static final String MOVE_FAILED_RESPONSE = "MoveFailed";

    /** An error code indicating that a place identified by a particular
     * place id does not exist. Usually generated by a failed moveTo
     * request. */
    public static final String NO_SUCH_PLACE = "m.no_such_place";

    /** An error code sent when a user requests to move to a new place but
     * they are in the middle of moving somewhere already. */
    public static final String MOVE_IN_PROGRESS = "m.move_in_progress";

    /** An error code sent when a user requests to move to a place, but
     * they are already in the requested place. */
    public static final String ALREADY_THERE = "m.already_there";
}
