//
// $Id: LocationCodes.java 3098 2004-08-27 02:12:55Z mdb $
//
// Narya library - tools for developing networked games
// Copyright (C) 2002-2004 Three Rings Design, Inc., All Rights Reserved
// http://www.threerings.net/code/narya/
//
// This library is free software; you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation; either version 2.1 of the License, or
// (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

package com.threerings.crowd.data {

import com.threerings.presents.data.InvocationCodes;

/**
 * Contains codes used by the location invocation services.
 */
public class LocationCodes extends InvocationCodes
{
    /** An error code indicating that a place identified by a particular
     * place id does not exist. Usually generated by a failed moveTo
     * request. */
    public static const NO_SUCH_PLACE :String = "m.no_such_place";

    /** An error code sent when a user requests to move to a new place but
     * they are in the middle of moving somewhere already. */
    public static const MOVE_IN_PROGRESS :String = "m.move_in_progress";

    /** An error code sent when a user requests to move to a place, but
     * they are already in the requested place. */
    public static const ALREADY_THERE :String = "m.already_there";
}
}
