//
// $Id: ZoneCodes.java,v 1.1 2001/12/04 00:31:58 mdb Exp $

package com.threerings.whirled.zone.client;

import com.threerings.whirled.client.SceneCodes;

/**
 * Contains codes used by the zone services.
 */
public interface ZoneCodes extends SceneCodes
{
    /** The module name for the zone services. */
    public static final String MODULE_NAME = "whirled!zone";

    /** An error code indicating that a zone identified by a particular
     * zone id does not exist. Usually generated by a failed moveTo
     * request. */
    public static final String NO_SUCH_ZONE = "m.no_such_zone";
}
