//
// $Id: SpotCodes.java,v 1.1 2001/12/14 00:12:32 mdb Exp $

package com.threerings.whirled.spot.client;

import com.threerings.crowd.chat.ChatCodes;
import com.threerings.crowd.client.LocationCodes;

/**
 * Contains codes used by the Spot invocation services.
 */
public interface SpotCodes extends ChatCodes, LocationCodes
{
    /** The module name for the Spot services. */
    public static final String MODULE_NAME = "whirled!spot";

    /** The message identifier for a cluster speak request message. */
    public static final String CLUSTER_SPEAK_REQUEST = "cspkreq";

    /** The message identifier for a changeLoc request. */
    public static final String CHANGE_LOC_REQUEST = "ChangeLoc";

    /** The response identifier for a successful changeLoc request. This
     * is mapped by the invocation services to a call to {@link
     * SpotSceneDirector#handleChangeLocSucceeded}. */
    public static final String CHANGE_LOC_SUCCEEDED_RESPONSE =
        "ChangeLocSucceeded";

    /** The response identifier for a failed changeLoc request. This is
     * mapped by the invocation services to a call to {@link
     * SpotSceneDirector#handleChangeLocFailed}. */
    public static final String CHANGE_LOC_FAILED_RESPONSE = "ChangeLocFailed";

    /** An error code indicating that a location is occupied. Usually
     * generated by a failed changeLoc request. */
    public static final String LOCATION_OCCUPIED = "m.location_occupied";
}
