#pragma once
// Generated by running python boxer.py in this directory

#include "presents/Streamable.h"
#include "presents/streamers/StreamableStreamer.h"

namespace presents { namespace box {
    class BoxedDouble : public Streamable{
    public:
        DECLARE_STREAMABLE();

        double value;

        static Shared<BoxedDouble> createShared (double value)
        {
            Shared<BoxedDouble> shared(new BoxedDouble);
            shared->value = value;
            return shared;
        }

        virtual void readObject(ObjectInputStream& in);
        virtual void writeObject(ObjectOutputStream& out) const;
    };
}}