#pragma once
// Generated by running python boxer.py in this directory

#include "presents/Streamable.h"
#include "presents/streamers/StreamableStreamer.h"

namespace presents { namespace box {
    class BoxedByte : public Streamable{
    public:
        DECLARE_STREAMABLE();

        int8 value;

        static Shared<BoxedByte> createShared (int8 value)
        {
            Shared<BoxedByte> shared(new BoxedByte);
            shared->value = value;
            return shared;
        }

        virtual void readObject(ObjectInputStream& in);
        virtual void writeObject(ObjectOutputStream& out) const;
    };
}}