#include "presents/stable.h"
#include "BoxedInt.h"
#include "presents/ObjectInputStream.h"
#include "presents/ObjectOutputStream.h"
// Generated by running python boxer.py in this directory

using namespace presents::box;

DEFINE_STREAMABLE("java.lang.Integer", BoxedInt);

void BoxedInt::readObject (ObjectInputStream& in)
{
    value = in.readInt();
}

void BoxedInt::writeObject (ObjectOutputStream& out) const
{
    out.writeInt(value);
}
