#pragma once
// Generated by running python boxer.py in this directory

#include "presents/Streamable.h"
#include "presents/streamers/StreamableStreamer.h"

namespace presents { namespace box {
    class BoxedInt : public Streamable{
    public:
        DECLARE_STREAMABLE();

        int32 value;

        static Shared<BoxedInt> createShared (int32 value)
        {
            Shared<BoxedInt> shared(new BoxedInt);
            shared->value = value;
            return shared;
        }

        virtual void readObject(ObjectInputStream& in);
        virtual void writeObject(ObjectOutputStream& out) const;
    };
}}