#include "presents/stable.h"
#include "BoxedFloat.h"
#include "presents/ObjectInputStream.h"
#include "presents/ObjectOutputStream.h"
// Generated by running python boxer.py in this directory

using namespace presents::box;

DEFINE_STREAMABLE("java.lang.Float", BoxedFloat);

void BoxedFloat::readObject (ObjectInputStream& in)
{
    value = in.readFloat();
}

void BoxedFloat::writeObject (ObjectOutputStream& out) const
{
    out.writeFloat(value);
}
