#pragma once
// Generated by running python boxer.py in this directory

#include "presents/Streamable.h"
#include "presents/streamers/StreamableStreamer.h"

namespace presents { namespace box {
    class BoxedFloat : public Streamable{
    public:
        DECLARE_STREAMABLE();

        float value;

        static Shared<BoxedFloat> createShared (float value)
        {
            Shared<BoxedFloat> shared(new BoxedFloat);
            shared->value = value;
            return shared;
        }

        virtual void readObject(ObjectInputStream& in);
        virtual void writeObject(ObjectOutputStream& out) const;
    };
}}