#pragma once
// Generated by running python boxer.py in this directory

#include "presents/Streamable.h"
#include "presents/streamers/StreamableStreamer.h"

namespace presents { namespace box {
    class BoxedBoolean : public Streamable{
    public:
        DECLARE_STREAMABLE();

        bool value;

        static Shared<BoxedBoolean> createShared (bool value)
        {
            Shared<BoxedBoolean> shared(new BoxedBoolean);
            shared->value = value;
            return shared;
        }

        virtual void readObject(ObjectInputStream& in);
        virtual void writeObject(ObjectOutputStream& out) const;
    };
}}