#include "presents/stable.h"
#include "BoxedShort.h"
#include "presents/ObjectInputStream.h"
#include "presents/ObjectOutputStream.h"
// Generated by running python boxer.py in this directory

using namespace presents::box;

DEFINE_STREAMABLE("java.lang.Short", BoxedShort);

void BoxedShort::readObject (ObjectInputStream& in)
{
    value = in.readShort();
}

void BoxedShort::writeObject (ObjectOutputStream& out) const
{
    out.writeShort(value);
}
