//
// $Id: LocationCodes.java,v 1.4 2002/08/14 19:07:49 mdb Exp $

package com.threerings.crowd.data;

import com.threerings.presents.data.InvocationCodes;

/**
 * Contains codes used by the location invocation services.
 */
public interface LocationCodes extends InvocationCodes
{
    /** An error code indicating that a place identified by a particular
     * place id does not exist. Usually generated by a failed moveTo
     * request. */
    public static final String NO_SUCH_PLACE = "m.no_such_place";

    /** An error code sent when a user requests to move to a new place but
     * they are in the middle of moving somewhere already. */
    public static final String MOVE_IN_PROGRESS = "m.move_in_progress";

    /** An error code sent when a user requests to move to a place, but
     * they are already in the requested place. */
    public static final String ALREADY_THERE = "m.already_there";
}
