#include "presents/stable.h"
#include "BoxedByte.h"
#include "presents/ObjectInputStream.h"
#include "presents/ObjectOutputStream.h"
// Generated by running python boxer.py in this directory

using namespace presents::box;

DEFINE_STREAMABLE("java.lang.Byte", BoxedByte);

void BoxedByte::readObject (ObjectInputStream& in)
{
    value = in.readByte();
}

void BoxedByte::writeObject (ObjectOutputStream& out) const
{
    out.writeByte(value);
}
