#include "presents/stable.h"
#include "BoxedDouble.h"
#include "presents/ObjectInputStream.h"
#include "presents/ObjectOutputStream.h"
// Generated by running python boxer.py in this directory

using namespace presents::box;

DEFINE_STREAMABLE("java.lang.Double", BoxedDouble);

void BoxedDouble::readObject (ObjectInputStream& in)
{
    value = in.readDouble();
}

void BoxedDouble::writeObject (ObjectOutputStream& out) const
{
    out.writeDouble(value);
}
