package com.threerings.presents.data {

import com.threerings.presents.client.GotTimeBaseListener;

import com.threerings.presents.dobj.InvocationResponseEvent;

// TODO: this will be autogenerated
public class GotTimeBaseMarshaller
    extends InvocationMarshaller_ListenerMarshaller
    implements GotTimeBaseListener
{
    public static const GOT_TIME_OID :int = 1;

    public function gotTimeOid (arg1 :int) :void
    {
        omgr.postEvent(new InvocationResponseEvent(
            callerOid, requestId, GOT_TIME_OID, [ arg1 ]));
    }

    public override function dispatchResponse (methodId :int, args :Array) :void
    {
        switch (methodId) {
        case GOT_TIME_OID:
            (listener as GotTimeBaseListener).gotTimeOid(args[0] as int);
            return;

        default:
            super.dispatchResponse(methodId, args);
            return;
        }
    }
}
}
