package com.threerings.presents.data {

import com.threerings.presents.client.GotTimeBaseListener;

import com.threerings.presents.dobj.InvocationResponseEvent;

// TODO: this will be autogenerated
public class TimeBaseMarshaller_GotTimeBaseMarshaller
    extends InvocationMarshaller_ListenerMarshaller
{
    public static const GOT_TIME_OID :int = 1;

    override public function dispatchResponse (methodId :int, args :Array) :void
    {
        switch (methodId) {
        case GOT_TIME_OID:
            (listener as GotTimeBaseListener).gotTimeOid(args[0] as int);
            return;

        default:
            super.dispatchResponse(methodId, args);
            return;
        }
    }
}
}
