/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_util_keybd_Keyboard */

#ifndef _Included_com_threerings_util_keybd_Keyboard
#define _Included_com_threerings_util_keybd_Keyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_util_keybd_Keyboard
 * Method:    setKeyRepeat
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_threerings_util_keybd_Keyboard_setKeyRepeat
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_threerings_util_keybd_Keyboard
 * Method:    isKeyRepeatEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_util_keybd_Keyboard_isKeyRepeatEnabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
